server:
  error:
    whitelabel:
      enabled: true
  port: 8088
application:
  version: @project.version@
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
      config:
        namespace: default
management:
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
